fix(ignore set): use safe_load instead of load
Failed test: https://jenkins.scylladb.com/view/master/job/scylla-master/job/driver-tests/job/
python-driver-matrix-test/810/console

Error: TypeError: load() missing 1 required positional argument: 'Loader'

In pyyaml 6.0 the yaml.load() function requires parameter loader=Loader. Instead of that for simple
YAML (str, int, lists), can use yaml.safe_load()